networks:
  laravelvue:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: laravelvue_nginx
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravelvue

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravelvue_php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravelvue
  mysql:
    image: mysql:5.7.29
    command: mysqld --sql_mode=""
    container_name: laravelvue_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravelvue
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret456
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravelvue
    volumes:
      - ./sql_scripts:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql

  composer:
    image: composer:latest
    user: "1000:1000"
    container_name: laravelvue_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    networks:
      - laravelvue

  npm:
    image: node:16
    container_name: laravelvue_npm
    user: "1000:1000"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: /bin/bash -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - laravelvue

  artisan:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravelvue_artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravelvue

  redis:
    image: redis:4.0
    container_name: laravelvue_redis
    ports:
      - "6379:6379"
    networks:
      - laravelvue

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8084:80
    environment:
      PMA_HOST: mysql
    networks:
      - laravelvue